# Site settings
name: 七条鱼
email: 347560833@qq.com
author: Keyu Zhao
url: http://goldofzky.github.io
resume_site: ""
github: https://github.com/goldofzky/
baseurl: ""
description: ahu在读本科，鶸一只
meta_description: 个人博客;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

